services:
  rng:
    image: brahimhamdi/rng
    container_name: rng
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  hasher:
    image: brahimhamdi/hasher
    container_name: hasher
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  webui:
    image: brahimhamdi/webui
    container_name: webui
    ports:
      - "8000:80"
    volumes:
      - "./webui/files/:/files/"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  redis:
    image: redis
    container_name: redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  worker:
    image: brahimhamdi/worker
    container_name: worker
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.8.16
    ports:
      - 9200:9200
  logstash:
    image: logstash:6.8.16
    container_name: logstash
    command: |
      -e '
      input {
        gelf { }
        heartbeat { }
      }
      filter {
        ruby {
          code => "
            event.to_hash.keys.each { |k| event[ k.gsub('"'.'"','"'_'"') ] = event.remove(k) if k.include?'"'.'"' }
          "
        }
      }
      output {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
        stdout {
          codec => rubydebug
        }
      }'

    ports:
      - 9600:9600
      - 12201:12201/udp
  kibana:
    image: kibana:6.8.16
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
